{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "General RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(toStartOfMinute(time)), count(1) as RPM FROM \"events\" WHERE $__timeFilter(toStartOfMinute(time)) AND   ( toStartOfMinute(time)  >= $__fromTime AND toStartOfMinute(time) <= $__toTime ) GROUP BY toStartOfMinute(time), toStartOfMinute(time) ORDER BY toStartOfMinute(time) ASC LIMIT 100"
    }
   ]
  },
  {
   "title": "RPM by datacenter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(toStartOfMinute(time)), count(1) as RPM, datacenter FROM \"events\" WHERE $__timeFilter(toStartOfMinute(time)) AND   ( toStartOfMinute(time)  >= $__fromTime AND toStartOfMinute(time) <= $__toTime ) GROUP BY datacenter, toStartOfMinute(time) ORDER BY toStartOfMinute(time) ASC LIMIT 100"
    }
   ]
  },
  {
   "title": "User Сonversions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(toStartOfMinute(time)), \n\nsum(type = 'view') / sum(1) as view,\nsum(type = 'cart') / sum(1) as cart,\nsum(type = 'purchase') / sum(1) as purchase\n\nFROM \"events\" WHERE $__timeFilter(toStartOfMinute(time)) AND   ( toStartOfMinute(time)  >= $__fromTime AND toStartOfMinute(time) <= $__toTime ) GROUP BY toStartOfMinute(time), toStartOfMinute(time) ORDER BY toStartOfMinute(time) ASC LIMIT 100",
     "selectedFormat": 4
    }
   ]
  }
 ]
}